language: c
cache:
  - apt: true

env:
    global:
        - LD_LIBRARY_PATH=/usr/local/lib
        - CURLS_INSTALL_PATH=$HOME/curl_install_path

addons:
    apt:
        config:
            retries: true
        sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
        packages:
            - cmake
            - gcc-7
            - gcc-8
            - lcov
            - clang-6.0
            - valgrind
            - libev-dev
            - libc-ares-dev
            - g++-8
            - libstdc++-8-dev
            - stunnel4
            - libidn2-0-dev
            - libssh2-1-dev
            - libssh-dev
            - krb5-user
            - autopoint  # for libpsl that needs autoreconf that uses gettext that needs it
            - libunistring-dev # for libidn2 needed by libpsl
            - libnss3-dev
            - gnutls-bin
            - clang-tidy-6.0

script:
  - ./buildconf
  - LDFLAGS="-static" PKG_CONFIG="pkg-config --static" ./configure --disable-shared --enable-static --with-ssl --prefix=$CURLS_INSTALL_PATH
  - make curl_LDFLAGS=-all-static
  - make install curl_LDFLAGS=-all-static
  - mv $CURLS_INSTALL_PATH/bin/curl $CURLS_INSTALL_PATH/bin/curls
  - $CURLS_INSTALL_PATH/bin/curls -help
